spring:
  config:
    import: "aws-parameterstore:/needapp/"
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    elasticsearch:
      uris: http://127.0.0.1:9200
      connection-timeout: 5s
      socket-timeout: 10s

app:
  environment:
    isProd: true

logging:
  level:
    org.springframework.cloud.aws: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate: INFO
    org.springframework: INFO