spring:
  config:
    activate:
      on-profile: render
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://needapp_postgres_user:p9482yGeWsjPEdmyhakO5vv6iy0BnmM6@dpg-d3p81o8dl3ps739kp6dg-a/needapp_postgres}
    username: ${SPRING_DATASOURCE_USERNAME:needapp_postgres_user}
    password: ${SPRING_DATASOURCE_PASSWORD:p9482yGeWsjPEdmyhakO5vv6iy0BnmM6}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    elasticsearch:
      uris: ${SPRING_DATA_ELASTICSEARCH_URIS}

server:
  port: ${PORT:10000}
  servlet:
    context-path: /api/v1

app:
  environment:
    isProd: true

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    org.springframework: INFO
    com.needbackend_app.needapp: INFO