spring:
  config:
    activate:
      on-profile: render
  datasource:
    url: ${SPRING_DATASOURCE_URL:${JDBC_DATABASE_URL:jdbc:${DATABASE_URL}}}
    username: ${SPRING_DATASOURCE_USERNAME:${JDBC_DATABASE_USERNAME:${DB_USERNAME}}}
    password: ${SPRING_DATASOURCE_PASSWORD:${JDBC_DATABASE_PASSWORD:${DB_PASSWORD}}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      data-source-properties:
        sslmode: require
        ssl: true
        sslfactory: org.postgresql.ssl.NonValidatingFactory
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    elasticsearch:
      uris: ${SPRING_DATA_ELASTICSEARCH_URIS}

server:
  port: ${PORT:10000}
  servlet:
    context-path: /api/v1

app:
  environment:
    isProd: true

logging:
  level:
    com.zaxxer.hikari: INFO
    org.hibernate: INFO
    org.springframework: INFO
    com.needbackend_app.needapp: INFO