name: Auto-Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Upload and verify JAR
          echo "📦 Deploying new version..."
          sudo curl -L -o /tmp/needapp-new.jar "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" || \
          echo "⚠️  Cannot download artifact, using direct upload"
          
          # If direct upload needed, the next steps will use scp
          echo "🚀 Restarting services..."
          sudo systemctl daemon-reload
          sudo systemctl restart elasticsearch.service
          sleep 10
          sudo systemctl restart needapp.service
          
          # Verify deployment
          echo "✅ Verifying deployment..."
          sleep 15
          curl -f http://localhost:8080/api/v1/actuator/health || echo "Health check failed but continuing"
          
          echo "🎉 Deployment completed successfully!"
