name: Auto-Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application-jar
        path: target/*.jar
        retention-days: 1

    - name: Deploy to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "target/*.jar"
        target: "/tmp"
        strip_components: 1

    - name: Restart services
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "📦 Deploying new version..."
          # Move the JAR to the application directory
          sudo mv /tmp/*.jar /opt/needapp/app.jar
          
          echo "🚀 Restarting services..."
          sudo systemctl daemon-reload
          sudo systemctl restart elasticsearch.service
          sleep 10
          sudo systemctl restart needapp.service
          
          # Verify deployment
          echo "✅ Verifying deployment..."
          sleep 15
          curl -f http://localhost:8080/api/v1/actuator/health || echo "Health check failed but continuing"
          
          echo "🎉 Deployment completed successfully!"
